[package]
name = "spacker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlua = "0.19.1"
colored = "2.0.0"
lazy_static = "1.4.0"
glob = "0.3.0"
zip = "0.6.2"
itertools = "0.10.3"